apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

images:
  - name: plan-service
    newName: image-registry.openshift-image-registry.svc:5000/advanced-rag/plan-service
    newTag: latest
