apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

images:
  - name: evaluator-service
    newName: image-registry.openshift-image-registry.svc:5000/advanced-rag/evaluator-service
    newTag: latest
