apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: plan-service
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  to:
    kind: Service
    name: plan-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
