apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vector-gateway
  annotations:
    haproxy.router.openshift.io/timeout: 120s
spec:
  to:
    kind: Service
    name: vector-gateway
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
