apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ministral-8b
  namespace: ministral
  annotations:
    openshift.io/display-name: ministral-8b
    security.opendatahub.io/enable-auth: "true"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    model:
      modelFormat:
        name: vllm
      runtime: vllm-ministral-runtime
      # Download from HuggingFace
      storageUri: hf://mistralai/Ministral-8B-Instruct-2410
      resources:
        requests:
          cpu: "4"
          memory: 24Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
